version: 2

jobs:
  test:
    working_directory: /go/src/github.com/uw-labs/proximo
    docker:
    - image: circleci/golang:1.12
      environment:
        GO111MODULE: "on"
        GOLANGCI_VERSION: "v1.15.0"
    steps:
    - run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s ${GOLANGCI_VERSION}
    - run: mv ./bin/golangci-lint $GOPATH/bin/ && rm -rf bin
    - checkout
    - run: go mod download
    - run: golangci-lint run --enable-all -D=lll,gochecknoglobals,gosec
    - run: go test -v -race -cover ./...
    - run: go build -o ./bin/server ./cmd/proximo-server
    - run: go build -o ./bin/client ./cmd/proximo-client

workflows:
  version: 2
  test:
    jobs:
      - test
